"""create posts table and update user and post models

Revision ID: b9262e8d91a4
Revises: 2b3b076c6310
Create Date: 2025-05-21 14:43:06.152723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9262e8d91a4'
down_revision: Union[str, None] = '2b3b076c6310'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('identification', table_name='user')
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_identification'), 'user', ['identification'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_identification'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.create_index('identification', 'user', ['identification'], unique=True)
    # ### end Alembic commands ###
